[tools]
powershell = "7"
python = "3.12"
uv = "latest"

[tasks.build]
run = "pwsh -NoProfile -File scripts/Invoke-Build-Faceless-Wheels.ps1"

[tasks.clean]
run = "pwsh -NoProfile -File scripts/Invoke-Clean-Faceless-Build.ps1"

[tasks.init]
run = "pwsh -NoProfile -File scripts/Invoke-Initialization.ps1"

[tasks.devel]
run = "pwsh -NoProfile -File scripts/Invoke-Devel.ps1"
# TODO: check if mise supports task dependencies or chains and make init upstream of devel
